### ISSUE TITLE
utcnow gives unexpected results

### ISSUE THREAD

**Issue by azmeuk** [simon-weber/python-libfaketime#35]
My system time is GMT+2. With freezegun, and without timezones, datetime.now() and datetime.utcnow() produce the same results. With python-libfaketime, the following test fails:

```python
    @fake_time('2000-01-01 10:00:05')                                                                                                                                                                              
    def test_fake_time_parses_easy_strings(self):                                                                                                                                                                  
        self.assertEqual(datetime.datetime.now(), datetime.datetime(2000, 1, 1, 10, 0, 5))                                                                                                                         
        self.assertEqual(datetime.datetime.utcnow(), datetime.datetime(2000, 1, 1, 10, 0, 5))  
```
```
======================================================================
FAIL: test_fake_time_parses_easy_strings (test.test_faketime.TestFaketime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/azmeuk/dev/python-libfaketime/test/test_faketime.py", line 47, in test_fake_time_parses_easy_strings
    self.assertEqual(datetime.datetime.utcnow(), datetime.datetime(2000, 1, 1, 10, 0, 5))
AssertionError: datetime.datetime(2000, 1, 1, 9, 0, 5) != datetime.datetime(2000, 1, 1, 10, 0, 5)

======================================================================
```

**Comment by azmeuk** [comment]
Fixed by #36.
